"""empty message

Revision ID: 3ea06b45ae51
Revises: 4de2d138a93f
Create Date: 2015-06-12 23:53:48.447007

"""

# revision identifiers, used by Alembic.
revision = '3ea06b45ae51'
down_revision = '4de2d138a93f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
