"""empty message

Revision ID: 47522bd0e1a6
Revises: 4ad51e5134b3
Create Date: 2015-06-13 00:01:05.318753

"""

# revision identifiers, used by Alembic.
revision = '47522bd0e1a6'
down_revision = '4ad51e5134b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
