"""empty message

Revision ID: 4ad51e5134b3
Revises: 3ea06b45ae51
Create Date: 2015-06-13 00:00:29.261514

"""

# revision identifiers, used by Alembic.
revision = '4ad51e5134b3'
down_revision = '3ea06b45ae51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
