"""empty message

Revision ID: 4de2d138a93f
Revises: 347f3b7c6379
Create Date: 2015-06-12 23:53:34.983872

"""

# revision identifiers, used by Alembic.
revision = '4de2d138a93f'
down_revision = '347f3b7c6379'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ssh_key', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keys')
    ### end Alembic commands ###
